# Generated by Django 4.2.1 on 2024-11-13 21:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=accounts.models.generate_username, max_length=100, null=True, unique=True),
        ),
    ]
